version: 3
endpoint: http://localhost:8082
admin_secret: myadminsecretkey
metadata_directory: metadata
migrations_directory: migrations
seeds_directory: seeds
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
