version: 3
endpoint: http://host.docker.internal:8080
admin_secret: myadminsecretkey
metadata_directory: metadata
migrations_directory: migrations
seeds_directory: seeds
actions:
  kind: synchronous
  handler_webhook_baseurl: http://host.docker.internal:3000
