FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

# Copy test files
COPY tests /app/tests

# Make sure karate-config.js is in the right place
RUN mkdir -p /app/tests/karate/src/test/resources
# Create directory for test results
RUN mkdir -p /app/target/karate-reports

# Download Postgres JDBC driver
ADD https://jdbc.postgresql.org/download/postgresql-42.7.2.jar /app/tests/postgresql-jdbc.jar

# Set default command
CMD ["java", "-cp", "/app/tests/karate.jar:/app/tests/postgresql-jdbc.jar:/app/tests/karate/src/test/resources", "com.intuit.karate.Main", "--configdir", "/app/tests/karate/src/test/resources", "/app/tests/karate/features"]
 