FROM openjdk:17

WORKDIR /app

# Copy test files
COPY tests /app/tests

# Make sure karate-config.js is in the right place
RUN mkdir -p /app/tests/karate/src/test/resources

# Set default command
CMD ["java", "-jar", "/app/tests/karate.jar", "--configdir", "/app/tests/karate/src/test/resources", "/app/tests/karate/features"] 