use neon::prelude::*;
use std::panic::{catch_unwind, AssertUnwindSafe};
use ultrahonk_no_std::{verify, ProofType, ProofVariant, PublicInput, PUB_SIZE};

const MAX_PROOF_BYTES: usize = 1024 * 1024;
const MAX_VERIFICATION_KEY_BYTES: usize = 128 * 1024;
const MAX_PUBLIC_INPUT_BYTES: usize = 1024 * 1024;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum DecodeError {
    Empty,
    InvalidHex,
    TooLarge,
    MisalignedPublicInputs,
}

fn decode_hex(value: &str, max_bytes: usize) -> Result<Vec<u8>, DecodeError> {
    let value = value.strip_prefix("0x").unwrap_or(value);
    if value.is_empty() {
        return Err(DecodeError::Empty);
    }
    if value.len() > max_bytes.saturating_mul(2) {
        return Err(DecodeError::TooLarge);
    }
    hex::decode(value).map_err(|_| DecodeError::InvalidHex)
}

fn decode_public_inputs(value: &str) -> Result<Vec<PublicInput>, DecodeError> {
    // An empty string is the canonical representation of zero public inputs.
    let value = value.strip_prefix("0x").unwrap_or(value);
    if value.is_empty() {
        return Ok(Vec::new());
    }

    let bytes = decode_hex(value, MAX_PUBLIC_INPUT_BYTES)?;
    if bytes.len() % PUB_SIZE != 0 {
        return Err(DecodeError::MisalignedPublicInputs);
    }

    bytes
        .chunks_exact(PUB_SIZE)
        .map(|chunk| {
            chunk
                .try_into()
                .map_err(|_| DecodeError::MisalignedPublicInputs)
        })
        .collect()
}

/// Verify a Keccak/EVM UltraHonk proof generated by Noir's `bb` backend.
///
/// The verifier accepts the raw `proof`, `vk`, and `public_inputs` binary
/// artifacts encoded as hexadecimal strings. Both ZK and plain UltraHonk
/// proof variants are supported. Every decoding or verification failure is
/// returned as `false`; untrusted input must never crash the Node process.
pub fn verify_proof_of_funds_hex(
    proof_hex: &str,
    verification_key_hex: &str,
    public_inputs_hex: &str,
) -> bool {
    let proof_bytes = match decode_hex(proof_hex, MAX_PROOF_BYTES) {
        Ok(bytes) => bytes,
        Err(_) => return false,
    };
    let verification_key = match decode_hex(verification_key_hex, MAX_VERIFICATION_KEY_BYTES) {
        Ok(bytes) => bytes,
        Err(_) => return false,
    };
    let public_inputs = match decode_public_inputs(public_inputs_hex) {
        Ok(inputs) => inputs,
        Err(_) => return false,
    };

    // A variant with an impossible byte length is rejected before invoking
    // the curve implementation. Usually exactly one variant matches.
    let verify_variant = |variant: ProofVariant| {
        if variant.log_n_from_byte_len(proof_bytes.len()).is_err() {
            return false;
        }

        let proof = match variant {
            ProofVariant::ZK => ProofType::ZK(proof_bytes.clone().into_boxed_slice()),
            ProofVariant::Plain => ProofType::Plain(proof_bytes.clone().into_boxed_slice()),
        };
        verify::<()>(&verification_key, &proof, &public_inputs).is_ok()
    };

    catch_unwind(AssertUnwindSafe(|| {
        verify_variant(ProofVariant::ZK) || verify_variant(ProofVariant::Plain)
    }))
    .unwrap_or(false)
}

fn verify_proof_of_funds(mut cx: FunctionContext) -> JsResult<JsBoolean> {
    let proof_hex = cx.argument::<JsString>(0)?.value(&mut cx);
    let verification_key = cx.argument::<JsString>(1)?.value(&mut cx);
    let public_inputs = cx.argument::<JsString>(2)?.value(&mut cx);

    let is_valid = verify_proof_of_funds_hex(&proof_hex, &verification_key, &public_inputs);
    Ok(cx.boolean(is_valid))
}

#[neon::main]
fn main(mut cx: ModuleContext) -> NeonResult<()> {
    cx.export_function("verifyProofOfFunds", verify_proof_of_funds)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rejects_malformed_hex() {
        assert!(!verify_proof_of_funds_hex("not-hex", "00", ""));
        assert!(!verify_proof_of_funds_hex("00", "not-hex", ""));
        assert!(!verify_proof_of_funds_hex("00", "00", "xyz"));
    }

    #[test]
    fn rejects_empty_proof_and_key() {
        assert!(!verify_proof_of_funds_hex("", "00", ""));
        assert!(!verify_proof_of_funds_hex("00", "", ""));
    }

    #[test]
    fn accepts_0x_prefix_when_decoding() {
        assert_eq!(decode_hex("0x00ff", 2), Ok(vec![0, 255]));
    }

    #[test]
    fn decodes_concatenated_public_input_fields() {
        let encoded = "00".repeat(PUB_SIZE * 2);
        assert_eq!(decode_public_inputs(&encoded).unwrap().len(), 2);
    }

    #[test]
    fn rejects_partial_public_input_fields() {
        assert_eq!(
            decode_public_inputs("00"),
            Err(DecodeError::MisalignedPublicInputs)
        );
    }

    #[test]
    fn enforces_input_size_limits_before_allocation() {
        let oversized = "00".repeat(MAX_PROOF_BYTES + 1);
        assert_eq!(
            decode_hex(&oversized, MAX_PROOF_BYTES),
            Err(DecodeError::TooLarge)
        );
    }
}
