use neon::prelude::*;
use std::panic::{catch_unwind, AssertUnwindSafe};
use ultrahonk_no_std::{verify, ProofType, ProofVariant, PublicInput, PUB_SIZE};

const MAX_PROOF_BYTES: usize = 1024 * 1024;
const MAX_VERIFICATION_KEY_BYTES: usize = 128 * 1024;
const BN254_SCALAR_MODULUS: PublicInput = [
    0x30, 0x64, 0x4e, 0x72, 0xe1, 0x31, 0xa0, 0x29, 0xb8, 0x50, 0x45, 0xb6, 0x81, 0x81, 0x58, 0x5d,
    0x28, 0x33, 0xe8, 0x48, 0x79, 0xb9, 0x70, 0x91, 0x43, 0xe1, 0xf5, 0x93, 0xf0, 0x00, 0x00, 0x01,
];

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum DecodeError {
    Empty,
    InvalidHex,
    InvalidThreshold,
    InvalidFieldSize,
    NonCanonicalField,
    TooLarge,
}

fn decode_hex(value: &str, max_bytes: usize) -> Result<Vec<u8>, DecodeError> {
    let value = value.strip_prefix("0x").unwrap_or(value);
    if value.is_empty() {
        return Err(DecodeError::Empty);
    }
    if value.len() > max_bytes.saturating_mul(2) {
        return Err(DecodeError::TooLarge);
    }
    hex::decode(value).map_err(|_| DecodeError::InvalidHex)
}

fn encode_threshold(threshold_stroops: &str) -> Result<PublicInput, DecodeError> {
    if threshold_stroops.is_empty() || !threshold_stroops.bytes().all(|byte| byte.is_ascii_digit())
    {
        return Err(DecodeError::InvalidThreshold);
    }

    let threshold = threshold_stroops
        .parse::<u64>()
        .map_err(|_| DecodeError::InvalidThreshold)?;
    let mut encoded = [0_u8; PUB_SIZE];
    encoded[PUB_SIZE - 8..].copy_from_slice(&threshold.to_be_bytes());
    Ok(encoded)
}

fn decode_balance_commitment(value: &str) -> Result<PublicInput, DecodeError> {
    let bytes = decode_hex(value, PUB_SIZE)?;
    let commitment: PublicInput = bytes
        .try_into()
        .map_err(|_| DecodeError::InvalidFieldSize)?;
    if commitment >= BN254_SCALAR_MODULUS {
        return Err(DecodeError::NonCanonicalField);
    }
    Ok(commitment)
}

/// Verify a Keccak/EVM UltraHonk proof generated by Noir's `bb` backend.
///
/// Public inputs are constructed in the circuit ABI order from an unsigned
/// 64-bit threshold in stroops and a 32-byte balance commitment. Both ZK and
/// plain UltraHonk proof variants are supported. Every decoding or verification
/// failure is returned as `false`; untrusted input must never crash Node.
pub fn verify_proof_of_funds_hex(
    proof_hex: &str,
    verification_key_hex: &str,
    threshold_stroops: &str,
    balance_commitment_hex: &str,
) -> bool {
    let proof_bytes = match decode_hex(proof_hex, MAX_PROOF_BYTES) {
        Ok(bytes) => bytes,
        Err(_) => return false,
    };
    let verification_key = match decode_hex(verification_key_hex, MAX_VERIFICATION_KEY_BYTES) {
        Ok(bytes) => bytes,
        Err(_) => return false,
    };
    let threshold = match encode_threshold(threshold_stroops) {
        Ok(input) => input,
        Err(_) => return false,
    };
    let balance_commitment = match decode_balance_commitment(balance_commitment_hex) {
        Ok(input) => input,
        Err(_) => return false,
    };
    let public_inputs = [threshold, balance_commitment];

    // A variant with an impossible byte length is rejected before invoking
    // the curve implementation. Usually exactly one variant matches.
    let verify_variant = |variant: ProofVariant| {
        if variant.log_n_from_byte_len(proof_bytes.len()).is_err() {
            return false;
        }

        let proof = match variant {
            ProofVariant::ZK => ProofType::ZK(proof_bytes.clone().into_boxed_slice()),
            ProofVariant::Plain => ProofType::Plain(proof_bytes.clone().into_boxed_slice()),
        };
        verify::<()>(&verification_key, &proof, &public_inputs).is_ok()
    };

    catch_unwind(AssertUnwindSafe(|| {
        verify_variant(ProofVariant::ZK) || verify_variant(ProofVariant::Plain)
    }))
    .unwrap_or(false)
}

fn verify_proof_of_funds(mut cx: FunctionContext) -> JsResult<JsBoolean> {
    let proof_hex = cx.argument::<JsString>(0)?.value(&mut cx);
    let verification_key = cx.argument::<JsString>(1)?.value(&mut cx);
    let threshold_stroops = cx.argument::<JsString>(2)?.value(&mut cx);
    let balance_commitment = cx.argument::<JsString>(3)?.value(&mut cx);

    let is_valid = verify_proof_of_funds_hex(
        &proof_hex,
        &verification_key,
        &threshold_stroops,
        &balance_commitment,
    );
    Ok(cx.boolean(is_valid))
}

#[neon::main]
fn main(mut cx: ModuleContext) -> NeonResult<()> {
    cx.export_function("verifyProofOfFunds", verify_proof_of_funds)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rejects_malformed_hex() {
        let commitment = "00".repeat(PUB_SIZE);
        assert!(!verify_proof_of_funds_hex(
            "not-hex",
            "00",
            "1",
            &commitment
        ));
        assert!(!verify_proof_of_funds_hex(
            "00",
            "not-hex",
            "1",
            &commitment
        ));
        assert!(!verify_proof_of_funds_hex("00", "00", "1", "xyz"));
    }

    #[test]
    fn rejects_empty_proof_and_key() {
        let commitment = "00".repeat(PUB_SIZE);
        assert!(!verify_proof_of_funds_hex("", "00", "1", &commitment));
        assert!(!verify_proof_of_funds_hex("00", "", "1", &commitment));
    }

    #[test]
    fn accepts_0x_prefix_when_decoding() {
        assert_eq!(decode_hex("0x00ff", 2), Ok(vec![0, 255]));
    }

    #[test]
    fn encodes_threshold_as_a_32_byte_public_field() {
        let threshold = 10_000_000_000_u64;
        let encoded = encode_threshold(&threshold.to_string()).unwrap();

        assert_eq!(&encoded[..PUB_SIZE - 8], &[0_u8; PUB_SIZE - 8]);
        assert_eq!(&encoded[PUB_SIZE - 8..], &threshold.to_be_bytes());
    }

    #[test]
    fn rejects_invalid_or_out_of_range_thresholds() {
        assert_eq!(encode_threshold("-1"), Err(DecodeError::InvalidThreshold));
        assert_eq!(encode_threshold("1.0"), Err(DecodeError::InvalidThreshold));
        assert_eq!(
            encode_threshold("18446744073709551616"),
            Err(DecodeError::InvalidThreshold)
        );
    }

    #[test]
    fn requires_a_32_byte_balance_commitment() {
        let commitment = "2a".repeat(PUB_SIZE);
        assert_eq!(decode_balance_commitment(&commitment), Ok([0x2a; PUB_SIZE]));
        assert_eq!(
            decode_balance_commitment("ab"),
            Err(DecodeError::InvalidFieldSize)
        );
        assert_eq!(
            decode_balance_commitment(&hex::encode(BN254_SCALAR_MODULUS)),
            Err(DecodeError::NonCanonicalField)
        );
    }

    #[test]
    fn enforces_input_size_limits_before_allocation() {
        let oversized = "00".repeat(MAX_PROOF_BYTES + 1);
        assert_eq!(
            decode_hex(&oversized, MAX_PROOF_BYTES),
            Err(DecodeError::TooLarge)
        );
    }
}
