blank_issues_enabled: true
contact_links:
  - name: Safetrust Backend issue
    url: https://github.com/safetrustcr/Backend/blob/main/.github/ISSUE_TEMPLATE/issues_template.md
    about: Please, create a backend issue for SafeTrust.
