table:
  name: hotels
  schema: public

columns:
  - name: id
    type: uuid
    default: uuid_generate_v4()
    is_nullable: false
    is_primary_key: true

  - name: name
    type: varchar(20)
    is_nullable: false

  - name: description
    type: varchar(50)
    is_nullable: true

  - name: address
    type: varchar(50)
    is_nullable: false

  - name: location_area
    type: varchar(20)
    is_nullable: true

  - name: coordinates
    type: geometry(Point,4326)
    is_nullable: false

  - name: created_at
    type: timestamptz
    default: now()
    is_nullable: false

  - name: updated_at
    type: timestamptz
    default: now()
    is_nullable: false

indexes:
  - name: idx_hotels_name
    columns:
      - name

  - name: idx_hotels_location_area
    columns:
      - location_area

  - name: idx_hotels_coordinates
    using: gist
    columns:
      - coordinates

select_permissions:
  - role: anonymous
    permission:
      columns:
        - id
        - name
        - description
        - address
        - location_area
        - coordinates
        - created_at
      filter: {}

  - role: user
    permission:
      columns:
        - id
        - name
        - description
        - address
        - location_area
        - coordinates
        - created_at
        - updated_at
      filter: {}

insert_permissions:
  - role: admin
    permission:
      columns:
        - name
        - description
        - address
        - location_area
        - coordinates
      check: {}

update_permissions:
  - role: admin
    permission:
      columns:
        - name
        - description
        - address
        - location_area
        - coordinates
        - updated_at
      filter: {}
      check: {}

delete_permissions:
  - role: admin
    permission:
      filter: {}

function:
  name: update_updated_at_column
  schema: public
  definition: |
    CREATE OR REPLACE FUNCTION update_updated_at_column()
    RETURNS TRIGGER AS $$
    BEGIN
      NEW.updated_at = NOW();
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;

triggers:
  - name: update_updated_at
    table: hotels
    schema: public
    definition:
      enable_manual: false
      events:
        - update
      function: update_updated_at_column
